name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            echo "🚀 Connecting to EC2 instance..."
            

            

            # Move into the repo
            cd 100xdevs-cicd-class || exit

            # Ensure we are on the correct branch and pull latest changes
            git checkout main
            git pull origin main

            echo "✅ Repository updated."

            # Load Node.js environment (if using nvm)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install dependencies
            echo "📦 Installing dependencies....."
            npm install

            # Build the Next.js app
            echo "🔨 Building Next.js application..."
            npm run build

            # Check if PM2 is installed, otherwise install it
            if ! command -v pm2 &> /dev/null; then
              echo "⚡ Installing PM2..."
              sudo npm install -g pm2
            fi

            # Stop any existing instance of the app
            pm2 delete "my-next-app" || true

            # Start the Next.js app with PM2
            echo "🚀 Starting application..."
            pm2 start npm --name "my-next-app" -- start

            # Save PM2 process list and startup script
            pm2 save
            pm2 startup systemd
